### ISSUE TITLE
ResultSystems\Validation\Validator::getValidRules(): Failed opening required

### ISSUE THREAD

**Issue by gfviegas** [resultsystems/validation#2]
<p>Using homestead (less likely to be a env trouble).</p>
<p>FatalErrorException in Validator.php line 376: ResultSystems\Validation\Validator::getValidRules(): Failed opening required '/home/vagrant/projetos/autentiq/API/vendor/resultsystems/validation/src/Validation/Respect/Rules.php' (include_path='/home/vagrant/projetos/autentiq/API/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/php:')</p>
<p>Just followed the steps, installed the lib, added the provider and tried to use a &quot;cpf&quot; rule on a validator, and this was thrown. Thoughts?</p>

**Comment by emtudo** [comment]
verifique se no seu projeto existe o arquivo: vendor/resultsystems/validation/src/Validation/Respect/Rules.php

Se não existir reinstale novamente o pacote.
