### ISSUE TITLE
Adicionar Inscrição Estadual

### ISSUE THREAD

**Issue by frankdors** [resultsystems/validation#5]
<p>Seria de grande valia, seria ter o validador de IE...</p>
<p>Pode se inspirar neste pacote... que tem inclusive também RG e Pis/Pasep
<a href="https://github.com/raphaklaus/br-validations">https://github.com/raphaklaus/br-validations</a></p>
<p>Parabéns pelo pacote...</p>

**Comment by juniorjc** [comment]
Fala ai galera.

Estou tentando usar a validação de CPF e estou recebendo o erro abaixo. 

Estou usando o Laravel 5.4, fiz todas as configurações e nada. Alguém poderia me ajudar.

`(1/1) BadMethodCallException
Method [validateCpf] does not exist.
in Validator.php (line 1110)
at Validator->__call('validateCpf', array('user.cpf', '12345678912', array(), object(Validator)))
in Validator.php (line 352)`
