### ISSUE TITLE
Restrição de checagem apenas para campos preenchidos

### ISSUE THREAD

**Issue by edukmattos** [resultsystems/validation#6]
<p>Parabéns pelo pacote !
Utilizo muito no Laravel 5.1 !
Atualizei para o Laravel 5.4 e está acontecendo um problema. Campos nao obrigatorios do tipo: telefone, email por exemplo, sao barrados pelo request informando que a formatacao está incorreta.
Tal informacao deveria ser apresentada caso houvesse o preenchimento de tais campos.
Estou fazendo alguma coisa errada ?</p>

**Comment by emtudo** [comment]
O laravel 5.4 tem um middleware que transforma tudo que é vazio em null, provável isso está influenciando.

**Comment by edukmattos** [comment]
Como conserto isso ?

**Comment by emtudo** [comment]
concerta? isso é uma melhoria.

O que vc pode fazer é ver estas regras aqui para saber qual pode usar em conjunto: https://laravel.com/docs/5.4/validation#available-validation-rules

Ou desativar o middleware no Kernel.php

**Comment by edukmattos** [comment]
Desculpa-me a ignorância mas qual seria esta melhoria ? Poderia me dar um exemplo ?
Posso desabilitar este middleware no kernel.php ?

**Comment by emtudo** [comment]
Pode desativar sim.
A melhor é que vc tem um campo que só é aceito nulo ou um valor no banco de dados, se ele for cadastro "" fica meio estranho não? para pesquisar depois?

Então este middleware transforma "" em null

**Comment by edukmattos** [comment]
ok.
Valeu pela dica !
