### ISSUE TITLE
Validate Não Existe

### ISSUE THREAD

**Issue by helderjosex** [resultsystems/validation#7]
<p>Instalei e configurei o pacote quando envio a página está aparecendo o seguinte erro:</p>
<p>(1/1) BadMethodCallExceptionMethod [validateCpf] does not exist.</p>
<p>Como faço para resolver?</p>
<p>Estou usando Laravel 5.4.28</p>

**Comment by emtudo** [comment]
Teve uma outra pessoa que teve o mesmo problema, e me contou que resolveu desinstalando, limpando o cache do composer e instalando novamente.

**Comment by helderjosex** [comment]
Tentei esse procedimento sem sucesso. Usei o comando composer clearcache

Também limpei o cache do laravel

**Comment by emtudo** [comment]
Não consegui reproduzir o erro
